### PR TITLE
Fix typescript typings

### LINKED ISSUE #15: Typescript definitions not working
Hi there,
I tried to use this module with the provided typescript definitions and got 

```
Argument of type '<HttpServer = any, HttpRequest = any, HttpResponse = any>(opts?: Options<HttpRequest> | undefined) => Plugin<HttpServer, HttpRequest, HttpResponse>' is not assignable to parameter of type '(instance: FastifyInstance<Server, IncomingMessage, ServerResponse>, options: { cookie: boolean; }, callback: (err?: FastifyError | undefined) => void) => void'.
  Types of parameters 'opts' and 'instance' are incompatible.
```

when using it via

```ts
server.register(fastifyCsrf, {cookie: true});
```

what actually worked for me are the following typings:

```ts
import {IncomingMessage, Server, ServerResponse} from "http";
import * as fastify from "fastify";
import {Options as TokenOptions} from "csrf";

declare module "fastify" {
    interface FastifyRequest {
        csrfToken(): string;
    }
}

interface Options<HttpRequest> extends TokenOptions {
    value?: (req: HttpRequest) => string;
    cookie?: fastify.CookieSerializeOptions | boolean;
    ignoreMethods?: Array<string>;
    sessionKey?: string;
}

declare const fastifyCsrf: fastify.Plugin<
    Server,
    IncomingMessage,
    ServerResponse,
    Options<ServerResponse>
>;

export = fastifyCsrf;
```

Would you accept a PR for this change? Or is there another way to make it work?

### PR DESCRIPTION
**Pull request by mksony**
Closes #15 

I added two commits, one with the changes which made the typings work as described in the issue and another one which would add a minimal test and related setup. 
Please let me know what you think about the included test, I can easily remove it if it should not be part of the regular tests 🙂 
It was inspired by e.g. https://github.com/fastify/fastify-cors

### CODE REVIEW

File: lib/fastifyCsrf.d.ts [hunk 1]
```diff
@@ -1,37 +1,32 @@
...
-    }
+interface Options extends TokenOptions {
+  key?: string;
+  value?: (req: fastify.FastifyRequest) => string;
+  cookie?: fastify.CookieSerializeOptions | boolean;
+  ignoreMethods?: Array<string>;
 }
 
-export = FastifyCsrfPlugin;
+declare const fastifyCsrf: fastify.Plugin<
```
Comment (jurca) [inline lib/fastifyCsrf.d.ts:25]: The `fastify.Plugin` type accepts only the `Options` type parameter, see: https://github.com/fastify/fastify/blob/master/types/plugin.d.ts#L10

This also makes `HttpServer`, `HttpRequest` and `HttpResponse` obsolete, so they can be removed from this file completely.

File: lib/fastifyCsrf.d.ts [hunk 2]
```diff
@@ -1,37 +1,32 @@
...
+}
 
-    interface Plugin<HttpServer, HttpRequest, HttpResponse>
-        extends fastify.Plugin<HttpServer, HttpRequest, HttpResponse, FastifyCsrfPlugin.Options<HttpRequest>> {
-    }
+interface Options extends TokenOptions {
+  key?: string;
+  value?: (req: fastify.FastifyRequest) => string;
+  cookie?: fastify.CookieSerializeOptions | boolean;
+  ignoreMethods?: Array<string>;
```
Comment (jurca) [inline lib/fastifyCsrf.d.ts:22]: Please preserve the code style of the main code. `string[]` is preferable to to `Array<string>`, and you should use tabs for indentation instead of 2 spaces (I know, indentation is not completely consistent in the code base. Let's improve that a little bit :)).

Also, please use single quotes instead of double.

File: package.json [hunk 3]
```diff
@@ -5,7 +5,8 @@
   "main": "lib/fastifyCsrf.js",
   "types": "lib/fastifyCsrf.d.ts",
   "scripts": {
-    "test": "tap test/*.js --cov"
+    "test": "tap test/*.js --cov && npm run typescript",
+    "typescript": "tsd"
```
Comment (jurca) [inline package.json:9]: Unfortunately, the naming here seems a little misleading and confusing. The script itself seems superfluous since it does not configure `tsd` using env variables or arguments. Could you change the `test` script to `tap test/*.js --cov && tsd`, please?

File: test/fastifyCsrf.test-d.ts [hunk 4]
```diff
@@ -0,0 +1,26 @@
+import * as fastify from "fastify";
```
Comment (jurca) [inline test/fastifyCsrf.test-d.ts:1]: Please update the code style as specified in comment above.

File: test/fastifyCsrf.test-d.ts [hunk 5]
```diff
@@ -0,0 +1,26 @@
...
+    return req.body["some_key"];
+  },
+});
+
+server.get("/", (request, reply) => {
+  var form = `
+      <form method = "post" action="/data">
+         <input type="text" name"field_name"/>
+         <input type="hidden" value="${request.csrfToken()}"
+	 name="_csrf /* this token can be sent in request header as well */"/>
```
Comment (jurca) [inline test/fastifyCsrf.test-d.ts:21]: I can see you have copy-pasted this from README :).

Unfortunately, JS comments (`/* */`) do not play nicely with HTML, could you, please, remove it?

File: package.json (hunk 3 above)
Comment (mksony) [reply package.json]: Yep you're right. I changed it to your suggestion. See 19cea1d

File: test/fastifyCsrf.test-d.ts (hunk 4 above)
Comment (mksony) [reply test/fastifyCsrf.test-d.ts]: Done, see 2b82425

File: test/fastifyCsrf.test-d.ts (hunk 5 above)
Comment (mksony) [reply test/fastifyCsrf.test-d.ts]: Yeah good, point 👍 See 188442c

File: lib/fastifyCsrf.d.ts (hunk 2 above)
Comment (mksony) [reply lib/fastifyCsrf.d.ts]: Agreed 🙂 See 2b82425.

File: lib/fastifyCsrf.d.ts (hunk 1 above)
Comment (mksony) [reply lib/fastifyCsrf.d.ts:25]: Yeah, I thought so too at first, but since we currently depend on `fastify@2.x` we need to look at https://github.com/fastify/fastify/blob/2.x/fastify.d.ts#L26 and there we the typings are less sophisticated unfortunately 😐

So should we keep it the way it is for now?

**Comment by mksony** [comment]
> @mksony Thanks a lot for submitting this PR!
> 
You're welcome. I am happy to contribute 🙂 

> There are, however, a few issues I would like you to take a look at.
> 

I addressed all the inline comments and for https://github.com/Tarang11/fastify-csrf/pull/17#discussion_r448752306 I would need feedback from you, please.

> Also, while I like the `tsd` tool, the version you used is not compatible with node.js 8, which makes the tests fail (see the [Checks](https://github.com/Tarang11/fastify-csrf/pull/17/checks) tab). Please try to use an older version that would work so that this plugin can maintain its current compatibility level.

Thanks for pointing this out. The people maintaining `tsd` are aware of the problem and merged a PR which addresses the problem just today. See https://github.com/SamVerschueren/tsd/pull/73. So either we wait until they publish the patch or we go with `0.11` instead of `0.12`. I downgraded for now and the tests pass.

Which option should we go for?

File: lib/fastifyCsrf.d.ts (hunk 1 above)
Comment (jurca) [reply lib/fastifyCsrf.d.ts:25]: Oh, my bad! Thanks for pointing this out :+1: .

Please keep it the way it is.
